require('dotenv').config()

const { sendSlackMessage } = require('./utils/slack.util');

console.log('🚀 Slack Notifier 🚀');

const sendMessage = async(message) => {
    await sendSlackMessage('This is generated by Notifier Test App');
}

sendMessage('hello world')
