require('dotenv').config()
const { sendSlackMessage } = require('./utils/slack.util');

console.log('🚀 Slack Notifier 🚀');
const sendMessage = async(message) => {
    await sendSlackMessage(message);
}
sendMessage('This is generated by Notifier Test App')
