const { WebClient, LogLevel } = require('@slack/web-api');

const options = {};
const web = new WebClient(process.env.SLACK_TOKEN, options);

const sendSlackMessage = async (message, channel = null) => {
    return new Promise(async (resolve, reject) => {
        const channelId = channel || process.env.SLACK_CHANNEL_ID;
        try {
            const resp = await web.chat.postMessage({
                text: 'This is generated by Notifier Test App',
                channel: channelId,
            });
            return resolve(true);
        } catch (error) {
            console.log('error', error)
            return resolve(true);
        }
    });
};

module.exports = {
    sendSlackMessage
};